version: 1
disable_existing_loggers: false
formatters:
  simple:
    format: "[%(levelname)s|%(module)s|L%(lineno)d] %(asctime)s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S%z"
  json:
    (): classes.JSONLogFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      thread_name: threadName
  yml:
    (): classes.YMLLogFormatter
    fmt_keys:
      level: levelname
      message: message
      timestamp: timestamp
      logger: name
      module: module
      function: funcName
      line: lineno
      thread_name: threadName
handlers:
  stdout:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  stderr:
    class: logging.StreamHandler
    level: WARNING
    formatter: simple
    stream: ext://sys.stderr
  file_json:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: logs/json_logs/managment_bot.log.jsonl
    maxBytes: 10000
    backupCount: 3
  file_yml:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: yml
    filename: logs/json_logs/managment_bot.log.jsonl
    maxBytes: 10000
    backupCount: 3
  queue_handler:
    class: logging.handlers.QueueHandler
    handlers:
      - stderr
      - file_json
      - stdout
    respect_handler_level: true
loggers:
  root:
    level: DEBUG
    handlers:
      - queue_handler
