name = "slshx-starter"
type = "javascript"

account_id = "42459c568b12d0902eeac887235b0c41"
workers_dev = false
route = "support.xenon.bot/*"
zone_id = "ba040eb427d023e4a612b0dd32e84fca"

compatibility_date = "2021-12-27"
compatibility_flags = []

[build]
command = "node scripts/build.js production"
[build.upload]
format = "modules"
main = "./index.mjs"

[env.development.build]
command = "node scripts/build.js development"
[env.development.build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
kv_persist = true
cache_persist = true
durable_objects_persist = true
global_async_io = true
